-- 005_create_produtos.sql
-- Cria a tabela `produtos` usada pelo painel de administração

CREATE TABLE IF NOT EXISTS public.produtos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text,
  preco numeric(10,2),
  descricao text,
  imagem text,
  destaque boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

-- Opcional: habilitar Row Level Security e policies para usuários autenticados
-- (Apenas use se você quiser que usuários autenticados via Supabase possam ler/gravar)
-- ALTER TABLE public.produtos ENABLE ROW LEVEL SECURITY;

-- CREATE POLICY select_authenticated ON public.produtos
--   FOR SELECT USING (auth.role() = 'authenticated');

-- CREATE POLICY write_authenticated ON public.produtos
--   FOR ALL
--   USING (auth.role() = 'authenticated')
--   WITH CHECK (auth.role() = 'authenticated');
